import type { Metadata } from "next";
import localFont from "next/font/local";
import "@libs/ui/src/app/globals.css";
import { ApolloProvider } from "@libs/network/src/config/apollo";
import { SessionProvider } from "@libs/ui/src/components/molecules/SessionProvider";
import { Header } from "@libs/ui/src/components/organisms/Header";
import { MenuItem } from "@libs/util/types";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const MENUITEMS: MenuItem[] = [
  { label: "Search", href: "/search" },
  { label: "Bookings", href: "/bookings" },
];

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <ApolloProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <Header menuItems={MENUITEMS} />
            {children}
          </body>
        </ApolloProvider>
      </SessionProvider>
    </html>
  );
}
