import { ReactNode } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@libs/ui/src/app/globals.css";
import { MenuItem } from "@libs/util/types";
import { ApolloProvider } from "@libs/network/src/config/apollo";
import { SessionProvider } from "@libs/ui/src/components/molecules/SessionProvider";
import { ToastContainer } from "@libs/ui/src/components/molecules/Toast";
import { Container } from "@libs/ui/src/components/atoms/Container";
import { Header } from "@libs/ui/src/components/organisms/Header";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Autospace | Admin",
  description: "Generated by create next app",
};

const MENUITEMS: MenuItem[] = [
  { label: "Garages", href: "/" },
  { label: "Admins", href: "/manageAdmins" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-25`}>
        <SessionProvider>
          <ApolloProvider>
            <Header type="admin" menuItems={MENUITEMS} />
            <Container>{children}</Container>
          </ApolloProvider>
        </SessionProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
